name: Build PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: ${{ github.event_name }}
    steps:
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Install Nats Server
        run: |
          curl -sf https://binaries.nats.dev/nats-io/nats-server/v2@main | PREFIX=. sh
          sudo mv nats-server /usr/local/bin
          nats-server -v
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build and Test
        run: chmod +x gradlew && ./gradlew clean test
      - name: Verify Javadoc
        run: ./gradlew --stacktrace --info javadoc
